version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
    target-branch: "main"
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "deps(npm)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    target-branch: "main"
    labels:
      - "dependencies"
    target-branch: "main"
    commit-message:
      prefix: "deps(uv)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
